// common action type
export const SET_UI_ELEMENT = 'SET_UI_ELEMENT';

// exception
export const EXCEPTION_TABLE_REQUEST = 'EXCEPTION_TABLE_REQUEST';
export const EXCEPTION_TABLE_SUCCESS = 'EXCEPTION_TABLE_SUCCESS';
export const EXCEPTION_TABLE_FAIL = 'EXCEPTION_TABLE_FAIL';
export const EXCEPTION_HISTOGRAM_REQUEST = 'EXCEPTION_HISTOGRAM_REQUEST';
export const EXCEPTION_HISTOGRAM_SUCCESS = 'EXCEPTION_HISTOGRAM_SUCCESS';
export const EXCEPTION_HISTOGRAM_FAIL = 'EXCEPTION_HISTOGRAM_FAIL';
export const EXCEPTION_PIE_REQUESET = 'EXCEPTION_PIE_REQUESET';
export const EXCEPTION_PIE_SUCCESS = 'EXCEPTION_PIE_SUCCESS';
export const EXCEPTION_PIE_FAIL = 'EXCEPTION_PIE_FAIL';

// material
export const LOGISTICS_DONUT_REQUEST = 'LOGISTICS_DONUT_REQUEST';
export const LOGISTICS_DONUT_SUCCESS = 'LOGISTICS_DONUT_SUCCESS';
export const LOGISTICS_DONUT_FAIL = 'LOGISTICS_DONUT_FAIL';
export const LOGISTICS_LINE_REQUEST = 'LOGISTICS_LINE_REQUEST';
export const LOGISTICS_LINE_SUCCESS = 'LOGISTICS_LINE_SUCCESS';
export const LOGISTICS_LINE_FAIL = 'LOGISTICS_LINE_FAIL';
export const LOGISTICS_TABLE_REQUEST = 'LOGISTICS_TABLE_REQUEST';
export const LOGISTICS_TABLE_SUCCESS = 'LOGISTICS_TABLE_SUCCESS';
export const LOGISTICS_TABLE_FAIL = 'LOGISTICS_TABLE_FAIL';
export const LOGISTICS_HISTOGRAM_REQUEST = 'LOGISTICS_HISTOGRAM_REQUEST';
export const LOGISTICS_HISTOGRAM_SUCCESS = 'LOGISTICS_HISTOGRAM_SUCCESS';
export const LOGISTICS_HISTOGRAM_FAIL = 'LOGISTICS_HISTOGRAM_FAIL';
