// common action types
export const SET_UI_ELEMENT = 'SET_UI_ELEMENT';

export const GET_COMMEENTS_REQUEST = 'GET_COMMEENTS_REQUEST';
export const GET_COMMEENTS_SUCCESS = 'GET_COMMEENTS_SUCCESS';
export const GET_COMMEENTS_FAIL = 'GET_COMMEENTS_FAIL';
