// common action types
export const SET_UI_ELEMENT = 'SET_UI_ELEMENT';

// exception
export const EXCEPTION_TABLE_REQUEST = 'EXCEPTION_TABLE_REQUEST';
export const EXCEPTION_TABLE_SUCCESS = 'EXCEPTION_TABLE_SUCCESS';
export const EXCEPTION_TABLE_FAIL = 'EXCEPTION_TABLE_FAIL';
export const EXCEPTION_STACK_REQUEST = 'EXCEPTION_STACK_REQUEST';
export const EXCEPTION_STACK_SUCCESS = 'EXCEPTION_STACK_SUCCESS';
export const EXCEPTION_STACK_FAIL = 'EXCEPTION_STACK_FAIL';
export const EXCEPTION_DONUT_REQUESET = 'EXCEPTION_DONUT_REQUESET';
export const EXCEPTION_DONUT_SUCCESS = 'EXCEPTION_DONUT_SUCCESS';
export const EXCEPTION_DONUT_FAIL = 'EXCEPTION_DONUT_FAIL';

// material
export const MATERIAL_DONUT_REQUEST = 'MATERIAL_DONUT_REQUEST';
export const MATERIAL_DONUT_SUCCESS = 'MATERIAL_DONUT_SUCCESS';
export const MATERIAL_DONUT_FAIL = 'MATERIAL_DONUT_FAIL';
export const MATERIAL_LINE_REQUEST = 'MATERIAL_LINE_REQUEST';
export const MATERIAL_LINE_SUCCESS = 'MATERIAL_LINE_SUCCESS';
export const MATERIAL_LINE_FAIL = 'MATERIAL_LINE_FAIL';
export const MATERIAL_TABLE_REQUEST = 'MATERIAL_TABLE_REQUEST';
export const MATERIAL_TABLE_SUCCESS = 'MATERIAL_TABLE_SUCCESS';
export const MATERIAL_TABLE_FAIL = 'MATERIAL_TABLE_FAIL';
export const MATERIAL_HISTOGRAM_REQUEST = 'MATERIAL_HISTOGRAM_REQUEST';
export const MATERIAL_HISTOGRAM_SUCCESS = 'MATERIAL_HISTOGRAM_SUCCESS';
export const MATERIAL_HISTOGRAM_FAIL = 'MATERIAL_HISTOGRAM_FAIL';
